# Generated by Django 5.2.14 on 2026-05-21 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('session_closing', 'Закрытие успеваемости')], max_length=50, verbose_name='тип уведомления')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('message', models.TextField(verbose_name='сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='прочитано в')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='education.academicperiod', verbose_name='учебный период')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='получатель')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('recipient', 'notification_type', 'period'), name='unique_notification_recipient_type_period')],
            },
        ),
    ]
