# Generated by Django 5.2.14 on 2026-05-21 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login_success', 'Успешный вход'), ('login_failed', 'Неудачный вход'), ('logout', 'Выход'), ('user_created', 'Пользователь создан'), ('user_updated', 'Пользователь изменен'), ('password_reset', 'Пароль сброшен'), ('grade_created', 'Оценка создана'), ('grade_updated', 'Оценка изменена'), ('attendance_created', 'Посещаемость создана'), ('attendance_updated', 'Посещаемость изменена'), ('report_generated', 'Отчет сформирован')], max_length=50, verbose_name='действие')),
                ('object_type', models.CharField(blank=True, max_length=100, verbose_name='тип объекта')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='представление объекта')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('request_id', models.CharField(blank=True, max_length=64, verbose_name='ID запроса')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='метаданные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='инициатор')),
            ],
            options={
                'verbose_name': 'запись аудита',
                'verbose_name_plural': 'записи аудита',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx')],
            },
        ),
    ]
