# Generated by Django 5.2.14 on 2026-05-21 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название группы')),
                ('enrollment_year', models.PositiveSmallIntegerField(verbose_name='год набора')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
            options={
                'verbose_name': 'учебная группа',
                'verbose_name_plural': 'учебные группы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название периода')),
                ('starts_at', models.DateField(verbose_name='дата начала')),
                ('ends_at', models.DateField(verbose_name='дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
            ],
            options={
                'verbose_name': 'учебный период',
                'verbose_name_plural': 'учебные периоды',
                'ordering': ('-starts_at', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название дисциплины')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='код дисциплины')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
            options={
                'verbose_name': 'дисциплина',
                'verbose_name_plural': 'дисциплины',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveIntegerField(unique=True, verbose_name='ID студента')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='дата зачисления')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='education.academicgroup', verbose_name='группа')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профиль студента',
                'verbose_name_plural': 'профили студентов',
                'ordering': ('group__name', 'student_id'),
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_number', models.CharField(max_length=50, unique=True, verbose_name='табельный номер')),
                ('position', models.CharField(blank=True, max_length=150, verbose_name='должность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'профиль преподавателя',
                'verbose_name_plural': 'профили преподавателей',
                'ordering': ('user__last_name', 'user__first_name'),
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='education.academicgroup', verbose_name='группа')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='education.academicperiod', verbose_name='учебный период')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='education.subject', verbose_name='дисциплина')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='education.teacherprofile', verbose_name='преподаватель')),
            ],
            options={
                'verbose_name': 'назначение преподавателя',
                'verbose_name_plural': 'назначения преподавателей',
                'ordering': ('period__starts_at', 'group__name', 'subject__name'),
                'constraints': [models.UniqueConstraint(fields=('teacher', 'subject', 'group', 'period'), name='unique_teacher_subject_group_period')],
            },
        ),
    ]
