# Generated by Django 5.2.14 on 2026-05-21 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('grades', 'Успеваемость'), ('attendance', 'Посещаемость')], max_length=20, verbose_name='тип отчета')),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX'), ('pdf', 'PDF')], max_length=10, verbose_name='формат файла')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='параметры')),
                ('file', models.FileField(blank=True, upload_to='reports/', verbose_name='файл')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время формирования')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_requests', to=settings.AUTH_USER_MODEL, verbose_name='запросил')),
            ],
            options={
                'verbose_name': 'сформированный отчет',
                'verbose_name_plural': 'сформированные отчеты',
                'ordering': ('-generated_at',),
            },
        ),
    ]
