# Generated by Django 5.2.14 on 2026-05-21 16:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название работы')),
                ('work_type', models.CharField(choices=[('classwork', 'Работа на занятии'), ('homework', 'Домашняя работа'), ('test', 'Контрольная работа'), ('exam', 'Экзамен'), ('other', 'Другое')], default='classwork', max_length=30, verbose_name='тип работы')),
                ('work_date', models.DateField(verbose_name='дата работы')),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='максимальный балл')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='вес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_works', to='education.teachingassignment', verbose_name='назначение преподавателя')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grade_works', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
            ],
            options={
                'verbose_name': 'работа в журнале',
                'verbose_name_plural': 'работы в журнале',
                'ordering': ('-work_date', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='оценка')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grades', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='education.studentprofile', verbose_name='студент')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_grades', to=settings.AUTH_USER_MODEL, verbose_name='обновил')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='journal.gradework', verbose_name='работа')),
            ],
            options={
                'verbose_name': 'оценка',
                'verbose_name_plural': 'оценки',
                'ordering': ('work__work_date', 'student__student_id'),
            },
        ),
        migrations.AddConstraint(
            model_name='gradework',
            constraint=models.UniqueConstraint(fields=('assignment', 'title', 'work_date'), name='unique_grade_work_assignment_title_date'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('work', 'student'), name='unique_grade_work_student'),
        ),
    ]
